# SQL queries for the UI
# 
# Usage of placeholders for parameterized queries:
#   - set or show queries: 
#       - %s
#   - other queries: 
#       - postgresql: $1 to $N
#       - sqlite3: ?
#       - mysql: ?
#       - mssql: @p1 to @pN
#      - clickhouse: %s


## set schema/database connection
set-schema:
  mssql: "use %s"
  mysql: ""
  postgresql: "set schema '%s'"
  sqlite3: ""
  clickhouse: "use %s"

set-schema-default:
  mssql: "use default_database"
  mysql: ""
  postgresql: "set search_path to default"
  sqlite3: ""
  clickhouse: "use default"

# ##
# current_database: # not tested
#   mssql: "select db_name()"
#   mysql: "select database()"
#   postgresql: "select current_database()"
#   sqlite3: "select database()"

# ##
# current_schema: # not tested
#   mssql: ""
#   mysql: ""
#   postgresql: "select current_schema()"
#   sqlite3: ""

##
ds-info:
  mssql: "select @@SERVERNAME as hostname, CONNECTIONPROPERTY('local_tcp_port') as port, db_name() as db_name, null, user_name() as user_name, @@version as version"
  mysql: "select @@hostname as 'hostname', @@port AS 'port', database() as 'database', null, current_user() as 'current_user', version() as version"
  postgresql: "select current_setting('listen_addresses') as listen, current_setting('port') as port, current_database() as database, current_setting('search_path') as search_path, user, version() as version"
  sqlite3: "select null, null, file, null, null, 'SQLite ' || sqlite_version() as version from pragma_database_list where name = 'main'"
  clickhouse: "select hostName() as hostname, getServerPort('tcp_port') as port, currentDatabase() as database, null, currentUser() as user, 'Clickhouse ' || version() as version"

version:
  mssql: "select @@version as version"
  mysql: "select version()"
  postgresql: "select version()"
  sqlite3: "select 'SQLite: ' || sqlite_version() as version"
  clickhouse: "select 'Clickhouse: ' || version() as version"


## explain query
explain:  
  mssql: "SET SHOWPLAN_ALL ON" # command will be executed, then query.
  mysql: "analyze" # query will be appended. No placeholder needed.
  postgresql: "explain analyze" # query will be appended. No placeholder needed.
  sqlite3: "EXPLAIN QUERY PLAN" # query will be appended. No placeholder needed.
  clickhouse: "EXPLAIN" # query will be appended. No placeholder needed.

## activity
activity:
  mssql: "SELECT r.session_id, r.start_time, r.status, r.command, r.sql_handle, t.text AS query_text FROM sys.dm_exec_requests AS r CROSS APPLY sys.dm_exec_sql_text(r.sql_handle) AS t WHERE r.session_id > 50"
  mysql: "show processlist"
  postgresql: "SELECT query_start, datname, state, query FROM pg_stat_activity where usename = current_user order by 1"
  sqlite3: ""
  clickhouse: "select user, current_database, query, elapsed, memory_usage, query_id from system.processes"

## object lists
schemas:
  mssql: "SELECT name FROM sys.databases order by 1"
  mysql: "" # show databases
  postgresql: "select schema_name from information_schema.schemata where schema_name not like 'pg\\_%' order by 1"
  sqlite3: ""
  clickhouse: "select distinct lower(name) as name FROM system.databases order by lower(name)" #"SHOW DATABASES"

tables:
  mssql: "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_TYPE = 'BASE TABLE' ORDER BY 1"
  mysql: "show full tables WHERE Table_Type = 'BASE TABLE'"
  postgresql: "select table_name from information_schema.tables where table_schema = (select current_schema) and table_type = 'BASE TABLE' order by 1"
  sqlite3: "select name from sqlite_schema where type = 'table' order by 1"
  clickhouse: "SELECT name FROM system.tables where database = currentDatabase() and engine <> 'View' order by 1"

views:
  mssql: "SELECT TABLE_NAME FROM INFORMATION_SCHEMA.VIEWS ORDER BY 1"
  mysql: "SHOW FULL TABLES WHERE Table_Type LIKE 'VIEW';"
  postgresql: "select table_name from information_schema.views where table_schema = (select current_schema) order by 1"
  sqlite3: "select name from sqlite_schema where type = 'view' order by 1"
  clickhouse: "SELECT name FROM system.tables where database = currentDatabase() and engine = 'View' ORDER BY name"

procedures:
  mssql: "SELECT name FROM sys.procedures ORDER BY 1"
  mysql: "select routine_name from information_schema.routines where routine_schema IN (SELECT SCHEMA())"
  postgresql: "SELECT routine_name routine_type FROM information_schema.routines WHERE routine_schema = (select current_schema) order by 1"
  sqlite3: ""
  clickhouse: ""

## object columns
table-columns:
  mssql: "SELECT col.COLUMN_NAME AS column_name, col.DATA_TYPE AS data_type, col.CHARACTER_MAXIMUM_LENGTH AS max_length, col.IS_NULLABLE AS is_nullable, CASE WHEN pk.COLUMN_NAME IS NOT NULL THEN 'YES' ELSE 'NO' END AS is_primary_key FROM INFORMATION_SCHEMA.COLUMNS col LEFT JOIN (SELECT ccu.COLUMN_NAME FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS tc JOIN INFORMATION_SCHEMA.CONSTRAINT_COLUMN_USAGE ccu ON tc.CONSTRAINT_NAME = ccu.CONSTRAINT_NAME WHERE tc.TABLE_NAME = @p1 AND tc.CONSTRAINT_TYPE = 'PRIMARY KEY') pk ON col.COLUMN_NAME = pk.COLUMN_NAME WHERE col.TABLE_NAME = @p1 ORDER BY col.ORDINAL_POSITION"
  mysql: "SHOW COLUMNS FROM %s"
  postgresql: "SELECT column_name as name, data_type as type, character_maximum_length as max_len, is_nullable as null, column_default as def from information_schema.columns where table_schema = (select current_schema) and table_name = $1 order by ordinal_position"
  sqlite3: "SELECT * FROM pragma_table_info(?) order by cid"
  clickhouse: "SELECT name, type, is_in_primary_key FROM system.columns where database = currentDatabase() and table = '%s' ORDER BY position"

view-columns:
  mssql: "SELECT col.COLUMN_NAME AS column_name, col.DATA_TYPE AS data_type, col.CHARACTER_MAXIMUM_LENGTH AS max_length, col.IS_NULLABLE AS is_nullable FROM INFORMATION_SCHEMA.COLUMNS col WHERE col.TABLE_NAME = @p1 ORDER BY col.ORDINAL_POSITION"
  mysql: "SHOW COLUMNS FROM %s"
  postgresql: "SELECT column_name as name, data_type as type, character_maximum_length as max_len, is_nullable as null, column_default as def from information_schema.columns where table_schema = (select current_schema) and table_name = $1 order by ordinal_position"
  sqlite3: "SELECT * FROM pragma_table_info(?) order by cid"
  clickhouse: "SELECT name, type, is_in_primary_key FROM system.columns where database = currentDatabase() and table = '%s' ORDER BY position"


## object definitions
table-definition:
  mssql: ""
  mysql: "show create table `%s`"
  postgresql: ""
  sqlite3: "select sql from sqlite_schema where type = 'table' and name = ?"
  clickhouse: "SHOW CREATE TABLE %s"

view-definition:
  mssql: "EXEC sp_helptext @p1"
  mysql: "show create view `%s`"
  postgresql: "SELECT pg_get_viewdef($1::regclass) as view_def"
  sqlite3: "select sql from sqlite_schema where type = 'view' and name = ?"
  clickhouse: "SHOW CREATE TABLE %s"

procedure-definition:
  mssql: "EXEC sp_helptext @p1"
  mysql: "show create procedure `%s`"
  postgresql: "SELECT pg_get_functiondef($1::regproc) as function_def"
  sqlite3: ""
  clickhouse: ""